### ISSUE TITLE
容器版本怎么

### ISSUE THREAD

**Issue by a52948** [helson-lin/ffandown#1]
用了你的容器版本，使用以下命令行也把容器启动起来了，能打开网页，但是没效果， 用的命令如下，是要以特权模式执行么？
docker run -itd -p 8181:8081 -v /mnt/media:/app/media h55205l/ffandown:v1

**Comment by helson-lin** [comment]
是什么平台，window/linux cpu是啥型号，嘛烦提供一下

**Comment by helson-lin** [comment]
> 用了你的容器版本，使用以下命令行也把容器启动起来了，能打开网页，但是没效果， 用的命令如下，是要以特权模式执行么？ docker run -itd -p 8181:8081 -v /mnt/media:/app/media h55205l/ffandown:v1

使用v2版本镜像，v1存在问题.
