### ISSUE TITLE
能不能钉钉通知出个教程

### ISSUE THREAD

**Issue by dreampjk** [helson-lin/ffandown#10]
搞好几天了  还是不成功

**Comment by helson-lin** [comment]
<img width="684" alt="image" src="https://github.com/helson-lin/ffandown/assets/84565447/a3b3c7db-4517-464b-b3be-54e2fce4b403">
创建钉钉机器人的时候，填写自定义关键词：文件

复制webhook地址，修改配置文件，webhookType: dingding webhook: 钉钉的地址 
修改完毕，重启服务

**Comment by dreampjk** [comment]
> 

谢谢  已经修改完成使用
