### ISSUE TITLE
Error: ffmpeg was killed with signal SIGSEGV

### ISSUE THREAD

**Issue by andyyang158** [helson-lin/ffandown#11]
使用暴力猴插件，可以获取m3u8链接，但是日志会显示ffmpeg was killed with signal SIGSEGV
无法下载

**Comment by helson-lin** [comment]
需要提供一下地址，问题可能性比较广泛，可能是地址有问题，也可能是进程出现异常

**Comment by andyyang158** [comment]
> 需要提供一下地址，问题可能性比较广泛，可能是地址有问题，也可能是进程出现异常

https://baikevideo.cdn.bcebos.com/media/mda-O0UHuOML8EqV0Umy/f56bdca139bbb786743212cc506c5baa_852x480_528000.m3u8

**Comment by helson-lin** [comment]
> > 需要提供一下地址，问题可能性比较广泛，可能是地址有问题，也可能是进程出现异常
> 
> https://baikevideo.cdn.bcebos.com/media/mda-O0UHuOML8EqV0Umy/f56bdca139bbb786743212cc506c5baa_852x480_528000.m3u8
> 
> 使用chrome插件点download 或者复制上面链接到webui中下载log中都显示error，我是用提供的docker命令安装的

我测试没有问题，是啥设备？你把log日志导出贴一下

**Comment by pgjeffrey** [comment]
同样的问题，使用的是v3版本。

<img width="1530" alt="image" src="https://github.com/helson-lin/ffandown/assets/32559583/ee94beed-0ef0-444b-bc6e-b96cc06ddd24">

**Comment by pgjeffrey** [comment]
> 同样的问题，使用的是v3版本。
> 
> <img alt="image" width="1530" src="https://private-user-images.githubusercontent.com/32559583/336332756-ee94beed-0ef0-444b-bc6e-b96cc06ddd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODM1MDIsIm5iZiI6MTcxNzQ4MzIwMiwicGF0aCI6Ii8zMjU1OTU4My8zMzYzMzI3NTYtZWU5NGJlZWQtMGVmMC00NDRiLWJjNmUtYjk2Y2MwNmRkZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2NDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZGYxOTA2OTVlMzJjYjQ3NTFlYjY2OGRlM2Y0YWRkMmEyMWI0ZDMyNDI4ZDRjOGJmYWY0ODFiMDQwMThjMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ia7Tw0DYS8fi7jHYp4kvbhIypuoVPDD2PPZPnykJX4">

群晖7的系统，docker安装

**Comment by helson-lin** [comment]
麻烦你使用最新的beta版本 v3已经不更新维护了

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/04/2024 14:42 |
| To | helson-lin/ffandown ***@***.***> |
| Cc | helson-lin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [helson-lin/ffandown] Error: ffmpeg was killed with signal SIGSEGV (Issue #11) |

同样的问题，使用的是v3版本。

群晖7的系统，docker安装
