### ISSUE TITLE
BUG：不支持linux/amd64的平台

### ISSUE THREAD

**Issue by 357341051** [helson-lin/ffandown#12]
root@armbian:~# docker run -d -p 8081:8081 -v /var/lib/docker/volumes/qbxiazai/_data/video:/app/media -v /var/lib/docker/volumes/qbxiazai/_data/config:/app/config h55205l/ffandown:v3
Unable to find image 'h55205l/ffandown:v3' locally
v3: Pulling from h55205l/ffandown
2d473b07cdd5: Already exists 
061a2b3f9f6a: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:2bf8302591d3ea93c2fbaaac2b79a390ab773651a7d968b090deab5dc0a480a6
Status: Downloaded newer image for h55205l/ffandown:v3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
591c2c8b6971d59524eaf987f7606d1bb4e69834fd2150a981540127f2987da4

![image](https://github.com/helson-lin/ffandown/assets/118408640/de0ab8a7-9663-4df0-846b-6ced6a1cfdcb)

**Comment by helson-lin** [comment]
晚上构建一下linux amd64的版本， 构建完毕。issue 通知你。

**Comment by helson-lin** [comment]
使用 h55205l/ffandown:linuxstatic 镜像
测试CPU: AMD EPYC 7K62 48-Core Processor

**Comment by 357341051** [comment]
好的，我试试，谢谢

**Comment by 357341051** [comment]
![image](https://github.com/helson-lin/ffandown/assets/118408640/0e6474cb-cc06-4960-ae10-289dc059ebb9)
root@armbian:~# docker run -d -p 8081:8081 -v /xiaohu/1panel/apps/alist/alist/data/data/aria2/downloads/app/media -v /var/lib/docker/volumes/qbxiazai/_data/config:/app/config h55205l/ffandown:linuxstatic
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
12ad700bb3cd749ab89e24245dcb020c8adb1cb06dca318e9a65c876f480d2de
![image](https://github.com/helson-lin/ffandown/assets/118408640/ba0263a1-0104-4a33-954b-9f4ea34aad09)

**Comment by 357341051** [comment]
> 使用 h55205l/ffandown：linuxstatic 镜像 测试CPU： AMD EPYC 7K62 48-Core Processor

好像不行

**Comment by helson-lin** [comment]
你这是电视盒子吧 要用arm的镜像；

**Comment by helson-lin** [comment]
`docker pull h55205l/ffandown:arm64` 你这是arm64的 不是am64 使用arm镜像就行了

**Comment by 357341051** [comment]
> `docker pull h55205l/ffandown:arm64` 你这是arm64的 不是am64 使用arm镜像就行了

![image](https://github.com/helson-lin/ffandown/assets/118408640/65e2d2dd-1090-4ea6-8b55-e5738a4ee02e)
安装了，但是没用，m3u8随便一个都一样

**Comment by helson-lin** [comment]
地址都不行？ 这版本之前测试了 没问题 给个地址 我看看

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月01日 15:06 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] BUG：不支持linux/amd64的平台 (Issue #12) |

docker pull h55205l/ffandown:arm64 你这是arm64的 不是am64 使用arm镜像就行了


安装了，但是没用，m3u8随便一个都一样

**Comment by 357341051** [comment]
> 地址都不行？ 这版本之前测试了 没问题 给个地址 我看看
> [...](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年11月01日 15:06 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] BUG：不支持linux/amd64的平台 (Issue #12) | docker pull h55205l/ffandown:arm64 你这是arm64的 不是am64 使用arm镜像就行了 安装了，但是没用，m3u8随便一个都一样 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

地址是可以的，比如：https://s8.fsvod1.com/20230524/bW0SZkHJ/index.m3u8，就是一直提示下载失败

**Comment by 357341051** [comment]
下载失败：Error: Error: ffmpeg exited with code 1: https://s8.fsvod1.com/20230524/bW0SZkHJ/index.m3u8: Input/output error

**Comment by helson-lin** [comment]
这个错误一般是： 
1. 输入的地址不能正常访问
2. 写入文件的地址没有权限


可以检查一下， docker跑的时候 查看一下下载目录地址是否有权限 写入 如果都没问题 我晚点排查一下


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月1日 16:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown] BUG：不支持linux/amd64的平台 (Issue #12) |

下载失败：Error: Error: ffmpeg exited with code 1: https://s8.fsvod1.com/20230524/bW0SZkHJ/index.m3u8: Input/output error

**Comment by helson-lin** [comment]
https://s8.fsvod1.com/20230524/bW0SZkHJ/index.m3u8 这个地址vlc 测试无法播放 你这个地址有问题吧

**Comment by helson-lin** [comment]
arm版本出现input/output error 是ffmpeg版本的问题。目前最新的arm镜像已经支持了。可以拉取最新的镜像测试 h55205l/ffandown:arm64

**Comment by helson-lin** [comment]
#16 https://github.com/helson-lin/ffandown/issues/16
