### ISSUE TITLE
希望可以增加自定义useragent

### ISSUE THREAD

**Issue by Mr-Mahui** [helson-lin/ffandown#14]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [ ] style questions
- [ ] other questions

### Download Url

please  paste the url below
if it's not a special url can't download, please provide more urls

### Question Details

有些m3u8网址是限制useragent，是否可以增加useragent为可选项

**Comment by helson-lin** [comment]
5.0.3Beta版本添加，可以自定义useragent
