### ISSUE TITLE
linux arm64平台，下载失败：Error: ffmpeg exited with code 1

### ISSUE THREAD

**Issue by Eoyz369** [helson-lin/ffandown#16]
(node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Object
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.end (_http_outgoing.js:811:13)
    at /snapshot/ffandown-master/bin/app.js:48:17
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `ffandown --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
下载失败 
下载失败：Error: Error: ffmpeg exited with code 1: https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8: Input/output error

使用的是h55205l/ffandown:arm64

**Comment by helson-lin** [comment]
换 http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8 这个地址测试一次 input/ouput error 一般都是地址无法被请求解析

**Comment by Eoyz369** [comment]
好的，这是换好之后的提示
下载失败 
下载失败：Error: Error: ffmpeg exited with code 1: http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8: Input/output error

**Comment by Eoyz369** [comment]
你好 我试了一下这个 http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8 

[ffdown]  downloading ffmpeg:https://pic.kblue.site/ffmpeg-4.4.1-linux-arm-64.zip
[ffandown] server running at:
    - http://127.0.0.1:8081/
    - http://172.17.0.5:8081/
下载失败 
下载失败：Error: Error: ffmpeg exited with code 1:

**Comment by Eoyz369** [comment]
> https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
重新启动了一下容器 然后再次测试了一下
[ffandown] server running at:
    - http://127.0.0.1:8081/
    - http://172.17.0.5:8081/
下载失败 
下载失败：Error: Error: ffmpeg exited with code 1: http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8: Input/output error

**Comment by helson-lin** [comment]
容器网络正常不 你可以进入容器ping一下baidu

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/28/2023 20:19 |
| To | helson-lin/ffandown ***@***.***> |
| Cc | helson-lin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [helson-lin/ffandown] Error (Issue #16) |

https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
重新启动了一下容器 然后再次测试了一下
[ffandown] server running at:
- http://127.0.0.1:8081/
- http://172.17.0.5:8081/
下载失败
下载失败：Error: Error: ffmpeg exited with code 1: http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8: Input/output error

**Comment by Eoyz369** [comment]
> 容器网络正常不 你可以进入容器ping一下baidu
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 11/28/2023 20:19 | | To | helson-lin/ffandown ***@***.***> | | Cc | helson-lin ***@***.***>, Comment ***@***.***> | | Subject | Re: [helson-lin/ffandown] Error (Issue #16) | https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 重新启动了一下容器 然后再次测试了一下 [ffandown] server running at: - http://127.0.0.1:8081/ - http://172.17.0.5:8081/ 下载失败 下载失败：Error: Error: ffmpeg exited with code 1: http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8: Input/output error — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
容器网络正常
[root@c5ef0c00d4d8 app]# ping baidu.com
PING baidu.com (110.242.68.66) 56(84) bytes of data.
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=1 ttl=53 time=49.8 ms
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=2 ttl=53 time=49.8 ms
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=3 ttl=53 time=50.5 ms
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=4 ttl=53 time=50.7 ms
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=5 ttl=53 time=50.2 ms
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=6 ttl=53 time=50.1 ms
64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=7 ttl=53 time=50.3 ms
^Z
[1]+  Stopped                 ping baidu.com
[root@c5ef0c00d4d8 app]#

**Comment by helson-lin** [comment]
稍等 我测试一下给您答复

**Comment by Eoyz369** [comment]
好的谢谢您
> 稍等 我测试一下给您答复

**Comment by helson-lin** [comment]
我昨晚看了一下 我家里的一台arm的确也是不行 但是mac m1 运行arm linux虚拟机正常。
错误原因是dns解析出现问题，没法正确请求到资源
你的机器是不是开了clash等软件

**Comment by Eoyz369** [comment]
没有clash软件 dns是114.114.114.114
> 我昨晚看了一下 我家里的一台arm的确也是不行 但是mac m1 运行arm linux虚拟机正常。 错误原因是dns解析出现问题，没法正确请求到资源 你的机器是不是开了clash等软件

**Comment by Eoyz369** [comment]
Good 非常感谢您

> 在网上找到了相似的问题，可能是FFMPEG出现了问题([https://github.com/SavageCore/node-ffprobe-installer/issues/66)，我自己编译一个版本，再试试看](https://github.com/SavageCore/node-ffprobe-installer/issues/66)%EF%BC%8C%E6%88%91%E8%87%AA%E5%B7%B1%E7%BC%96%E8%AF%91%E4%B8%80%E4%B8%AA%E7%89%88%E6%9C%AC%EF%BC%8C%E5%86%8D%E8%AF%95%E8%AF%95%E7%9C%8B)

**Comment by helson-lin** [comment]
删除容器重新运行一下 应该就可以了

**Comment by Eoyz369** [comment]
[ffdown]  downloading ffmpeg:https://pic.kblue.site/ffmpeg-4.4.1-linux-arm-64.zip
[ffandown] server running at:
    - http://127.0.0.1:8081/
    - http://172.17.0.5:8081/
下载失败 
下载失败：Error: Error: ffmpeg exited with code 1

**Comment by Eoyz369** [comment]
是不是我的操作问题

**Comment by helson-lin** [comment]
你是啥设备 cpu是啥 我测试过了这个依赖已经没问题了

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/29/2023 23:17 |
| To | helson-lin/ffandown ***@***.***> |
| Cc | helson-lin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [helson-lin/ffandown] Error (Issue #16) |

是不是我的操作问题

**Comment by Eoyz369** [comment]
斐讯N1

**Comment by helson-lin** [comment]
我用的rk3568,已经更新最新镜像 在rk3568测试没问题了。 h55205l/ffandown:arm64 删除镜像拉取最新的试试看

**Comment by helson-lin** [comment]
> RK3318 CentOS 7.9.2009 (AltArch) 不支持的话就不麻烦您了， 真的很感谢您的作品。

h55205l/ffandown:arm64 你用最新的版本试试 测试平台rk3569

**Comment by Eoyz369** [comment]
> > RK3318 CentOS 7.9.2009 (AltArch) 不支持的话就不麻烦您了， 真的很感谢您的作品。
> 
> h55205l/ffandown:arm64 你用最新的版本试试 测试平台rk3569

好的晚点我试一下
