### ISSUE TITLE
m3u8文件的网址后缀必须是.m3u8吗

### ISSUE THREAD

**Issue by Mr-Mahui** [helson-lin/ffandown#19]
###  ISSUE Type

- [x] download failed
- [ ] new features
- [ ] style questions
- [ ] other questions

### Download Url

链接不是以.m3u8结尾

### Question Details

链接不是以.m3u8结尾，通过postman 设置useragent之后调用，会正常请求出数据，但是在5.0.3及之后版本似乎填了useragent代理都不能正常下载，请问是否有相关的限制

**Comment by helson-lin** [comment]
默认是不是常规的m3u8 rtsp rtmp是不能提交的 ，
前端页面进行的提交限制的，后端没有限制所以可以调用


5.0.3 也是前端限制的，如果调用失败 你发出请求参数和响应
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月4日 11:32 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [helson-lin/ffandown] m3u8文件的网址后缀必须是.m3u8吗 (Issue #19) |

ISSUE Type
download failed
new features
style questions
other questions
Download Url

链接不是以.m3u8结尾

Question Details

链接不是以.m3u8结尾，通过postman 设置useragent之后调用，会正常请求出数据，但是在5.0.3及之后版本似乎填了useragent代理都不能正常下载，请问是否有相关的限制

**Comment by Mr-Mahui** [comment]
链接 https://files.yuchenglw.com/index/m3u8/id/22446
useragent 为 iPhone 大佬请试一下

**Comment by helson-lin** [comment]
好的 我测试一下
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月6日 11:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown] m3u8文件的网址后缀必须是.m3u8吗 (Issue #19) |

链接 https://files.yuchenglw.com/index/m3u8/id/22446
useragent 为 iPhone 大佬请试一下

**Comment by helson-lin** [comment]
不好意思 是后端我做了处理, m3u8 or rtmp、 rtsp，才可以正常下载。我优化一下链接的处理吧，根据相应头来判断文件类型

**Comment by Mr-Mahui** [comment]
好的，辛苦大佬，版本更新时候记得Q一下我

**Comment by helson-lin** [comment]
你提供的地址404了有新的嘛 问题修复了 需要测试一下，版本需要等等。
我在优化github actions的流程有点小问题目前

**Comment by Mr-Mahui** [comment]
https://files.yuchenglw.com/index/m3u8/id/6890

**Comment by Mr-Mahui** [comment]
你试试这个  https://files.yuchenglw.com/index/m3u8/id/6890 或者有TG联系方式之类的可以加一下，其他都可以给你，这个地方不好粘贴太多

**Comment by helson-lin** [comment]
TG发我吧 你这个地址好像有时效

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月11日 09:34 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown] m3u8文件的网址后缀必须是.m3u8吗 (Issue #19) |

你试试这个 https://files.yuchenglw.com/index/m3u8/id/6890 或者有TG联系方式之类的可以加一下，其他都可以给你，这个地方不好粘贴太多

**Comment by helson-lin** [comment]
![image](https://github.com/helson-lin/ffandown/assets/84565447/b5e71b65-02ce-4f7d-ab84-b33a3635a6f5)
TG发我吧 你这个地址好像有时效
 扫码就行了

**Comment by helson-lin** [comment]
v5.0.6-Beta已经更新：支持了非m3u8结尾的地址的提交。

**Comment by Mr-Mahui** [comment]
好的，我试试

**Comment by helson-lin** [comment]
没有问题 我关闭issue了

**Comment by Mr-Mahui** [comment]
没问题了，谢谢
