### ISSUE TITLE
5.0.6版本不能用

### ISSUE THREAD

**Issue by jk9527** [helson-lin/ffandown#20]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [ ] style questions
- [ ] other questions

### Download Url

please  paste the url below
if it's not a special url can't download, please provide more urls

### Question Details

please paste your question details below

![image](https://github.com/helson-lin/ffandown/assets/40191829/c0ff6b7a-c921-428c-b97c-77c34597afaf)

试了mac x64 和win 版本错误一样

**Comment by helson-lin** [comment]
Beta版本GitHub actions构建的时候sqllite 依赖没有打进去 我今晚更新 等会下架版本

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月12日 10:18 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 5.0.6版本不能用 (Issue #20) |

ISSUE Type
download failed
new features
style questions
other questions
Download Url

please paste the url below
if it's not a special url can't download, please provide more urls

Question Details

please paste your question details below

image.png (view on web)

试了mac x64 和win 版本错误一样

**Comment by jk9527** [comment]
好的，先退回5.0.5使用

**Comment by helson-lin** [comment]
5.0.6-Beta已经更新

**Comment by jk9527** [comment]
5.0.6-Beta还没来得及下载，就删除了，现在最新只有4.2.2。本着有新版本，就得用最新版。自己百度怎么打包，打包最新代码也提示sqlite3依赖问题。将[package](https://github.com/helson-lin/ffandown/tree/master/package)复制到ffandown-master\node_modules\sqlite3\lib\binding问题依然存在，根据报错提示C:\snapshot\ffandown-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node，将package下[napi-v3-win32-unknown-x64](https://github.com/helson-lin/ffandown/tree/master/package/napi-v3-win32-unknown-x64)更改为node-v83-win32-x64后，再重新打包测试正常运行。在mac os上测试将[napi-v6-darwin-unknown-x64](https://github.com/helson-lin/ffandown/tree/master/package/napi-v6-darwin-unknown-x64)为node-v83-darwin-x64打包也正常运行。

测试时删除了全平台打包，只做了单平台打包测试

**Comment by helson-lin** [comment]
是因为5.0.6-Beat release 存在相同的问题就删除了，Docker版本正常
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月16日 14:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 5.0.6版本不能用 (Issue #20) |

5.0.6-Beta还没来得及下载，就删除了，现在最新只有4.2.2。本着有新版本，就得用最新版。自己百度怎么打包，打包最新代码也提示sqlite3依赖问题。将package复制到ffandown-master\node_modules\sqlite3\lib\binding问题依然存在，根据报错提示C:\snapshot\ffandown-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node，将package下napi-v3-win32-unknown-x64更改为node-v83-win32-x64后，再重新打包测试正常运行。在mac os上测试将napi-v6-darwin-unknown-x64为node-v83-darwin-x64打包也正常运行。

测试时删除了全平台打包，只做了单平台打包测试

**Comment by helson-lin** [comment]
👍 
原因是不同的node版本对应的文件夹名称不一致，pkg 不会打包原生的依赖，你可以不修改和复制node文件夹到node_modules下面。
直接将.node文件放在程序同层就可以了。


但是针对GitHub actions 自动打包目前还没有啥好的方案。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月16日 14:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 5.0.6版本不能用 (Issue #20) |

5.0.6-Beta还没来得及下载，就删除了，现在最新只有4.2.2。本着有新版本，就得用最新版。自己百度怎么打包，打包最新代码也提示sqlite3依赖问题。将package复制到ffandown-master\node_modules\sqlite3\lib\binding问题依然存在，根据报错提示C:\snapshot\ffandown-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node，将package下napi-v3-win32-unknown-x64更改为node-v83-win32-x64后，再重新打包测试正常运行。在mac os上测试将napi-v6-darwin-unknown-x64为node-v83-darwin-x64打包也正常运行。

测试时删除了全平台打包，只做了单平台打包测试

**Comment by jk9527** [comment]
> 👍 原因是不同的node版本对应的文件夹名称不一致，pkg 不会打包原生的依赖，你可以不修改和复制node文件夹到node_modules下面。 直接将.node文件放在程序同层就可以了。 但是针对GitHub actions 自动打包目前还没有啥好的方案。 ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年01月16日 14:47 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [helson-lin/ffandown] 5.0.6版本不能用 (Issue #20) | 5.0.6-Beta还没来得及下载，就删除了，现在最新只有4.2.2。本着有新版本，就得用最新版。自己百度怎么打包，打包最新代码也提示sqlite3依赖问题。将package复制到ffandown-master\node_modules\sqlite3\lib\binding问题依然存在，根据报错提示C:\snapshot\ffandown-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node，将package下napi-v3-win32-unknown-x64更改为node-v83-win32-x64后，再重新打包测试正常运行。在mac os上测试将napi-v6-darwin-unknown-x64为node-v83-darwin-x64打包也正常运行。 测试时删除了全平台打包，只做了单平台打包测试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

感谢解答，又试了下放到同目录也可以正常运行，自己鼓捣虽然能用，也不知道啥原因
