### ISSUE TITLE
h55205l/ffandown:arm64镜像拉取不了

### ISSUE THREAD

**Issue by dreampjk** [helson-lin/ffandown#21]
###  ISSUE Type

- [x] download failed
- [ ] new features
- [ ] style questions
- [ ] other questions

### Download Url

please  paste the url below
if it's not a special url can't download, please provide more urls

### Question Details

please paste your question details below

**Comment by dreampjk** [comment]
docker pull h55205l/ffandown:arm64

**Comment by dreampjk** [comment]
> 我晚上看下
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年01月19日 17:46 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [helson-lin/ffandown] h55205l/ffandown:arm64镜像拉取不了 (Issue #21) | docker pull h55205l/ffandown:arm64 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

请问还能不能下载

**Comment by dreampjk** [comment]
Error response from daemon: manifest for h55205l/ffandown:arm64 not found: manifest unknown: manifest unknown   
显示的这个

**Comment by dreampjk** [comment]
latest可以下载

**Comment by dreampjk** [comment]
> 我晚上看下
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年01月19日 17:46 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [helson-lin/ffandown] h55205l/ffandown:arm64镜像拉取不了 (Issue #21) | docker pull h55205l/ffandown:arm64 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
请问还能不能下载

**Comment by dreampjk** [comment]
Error: Cannot find ffmpeg  下载不了视频

**Comment by helson-lin** [comment]
会自动下载ffmpeg的 下载失败了嘛

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月26日 06:54 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] h55205l/ffandown:arm64镜像拉取不了 (Issue #21) |

Error: Cannot find ffmpeg 下载不了视频

**Comment by dreampjk** [comment]
下载失败

下载会在视频名称末尾添加一串数字  这个怎么取消

**Comment by helson-lin** [comment]
这个是为了防止重复添加任务加的随机字符串 没有开配置

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月26日 07:21 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] h55205l/ffandown:arm64镜像拉取不了 (Issue #21) |

下载失败

下载会在视频名称末尾添加一串数字 这个怎么取消

**Comment by helson-lin** [comment]
ffmpeg如果下载失败可以吧lib 目录映射出去然后手动下载依赖

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月26日 07:21 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] h55205l/ffandown:arm64镜像拉取不了 (Issue #21) |

下载失败

下载会在视频名称末尾添加一串数字 这个怎么取消

**Comment by helson-lin** [comment]
重启一下容器 ffmpeg依赖可以下载了 cdn的资源丢了

**Comment by helson-lin** [comment]
没有问题 我关闭issue了
