### ISSUE TITLE
暴力猴插件不生效

### ISSUE THREAD

**Issue by ImUlee** [helson-lin/ffandown#25]
我在暴力猴内添加脚本后并修改了脚本内的 ffandown 地址
但是脚本好像不生效唉，我看 ffandown docs 里演示视频的是 age动漫站，然后我也去播放但是不显示抓取的按钮耶..

![Snipaste_2024-03-04_11-20-15](https://github.com/helson-lin/ffandown/assets/39436205/dc3f40c8-7539-4a7d-b78d-15683ec92ecc)

**Comment by helson-lin** [comment]
控制台有错误嘛 我晚上看下

**Comment by helson-lin** [comment]
测试了其他网站没问题

**Comment by helson-lin** [comment]
> > 测试了其他网站没问题
> 
> 
> 
> 我在研究研究。莫非我测试的几个都不行？

都是啥网站 我回去看看
