### ISSUE TITLE
arm64平台，增加任务成功，但是在管理看不到正在下载，下载完也没记录。

### ISSUE THREAD

**Issue by bnaand** [helson-lin/ffandown#27]
arm64平台，docker版
添加任务成功，也可以正常下载，但是在管理正在下载，下载完成均没记录。

**Comment by helson-lin** [comment]
那个版本的提供一下版本号

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月16日 17:31 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] arm64平台，增加任务成功，但是在管理看不到正在下载，下载完也没记录。 (Issue #27) |

arm64平台，docker版
添加任务成功，也可以正常下载，但是在管理正在下载，下载完成均没记录。

**Comment by bnaand** [comment]
在portainer管理器看到的标签：h55205l/ffandown:arm64 
ID标签   sha256:41ab6cfd6964f02a1eb337f4522a21d40825f0d1b87831cd3ce888efe258f994
平台：Armbian OS 24.5.0 Jammy with Linux 6.1.81
CPU：RK3568

**Comment by helson-lin** [comment]
周末提供最新版本arm镜像

**Comment by bnaand** [comment]
arm版的docker镜像什么时候更新？ 我在docker hub下载到的还是2个月前的镜像。
