### ISSUE TITLE
请增加设置下载的子目录的功能，不同类型的视频放到不同的子目录里

### ISSUE THREAD

**Issue by trader7z** [helson-lin/ffandown#29]
请增加设置下载的子目录的功能，不同类型的视频放到不同的子目录里，web和api都需要，谢谢

**Comment by helson-lin** [comment]
如何区分不同类型的视频文件？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月27日 06:16 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 请增加设置下载的子目录的功能，不同类型的视频放到不同的子目录里 (Issue #29) |

请增加设置下载的子目录的功能，不同类型的视频放到不同的子目录里，web和api都需要，谢谢

**Comment by trader7z** [comment]
就是增加一个目录选项，可以列出已经存在的子目录，选择即可。同时可以新建子目录。这样可以实现不同目录存放不同的视频。

**Comment by helson-lin** [comment]
最新v5.0.8_beta支持目录自定义
