### ISSUE TITLE
m3u8直播流的下载到中途中断了的文件无法播放

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#30]
###  ISSUE Type
- [x] download failed
- [x] new features
- [ ] style questions
- [ ] other questions

非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。

### Download Url

[例如这个链接](https://iclasscloud.cretech.cn/livecloudceshi/#)里的直播，或者其他直播流类型的m3u8

### Question Details

[这个链接](https://iclasscloud.cretech.cn/livecloudceshi/#)中的视频都是直播流的m3u8，因为这个平台的视频没有回放，我想做的事情是，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。

**Comment by helson-lin** [comment]
你是创建了多个下载任务然后手动合成的嘛

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月01日 16:23 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) |

ISSUE Type
download failed
new features
style questions
other questions

非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。

Download Url

这个链接，中的视频都是直播流的m3u8，我想达到的效果是，因为没有回放，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。

Question Details

please paste your question details below

**Comment by asong2022** [comment]
> 你是创建了多个下载任务然后手动合成的嘛
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 16:23 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | ISSUE Type download failed new features style questions other questions 非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。 Download Url 这个链接，中的视频都是直播流的m3u8，我想达到的效果是，因为没有回放，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。 Question Details please paste your question details below — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

您好，我不是创建了多个下载任务，我是docker里的ffandown，刚刚这个平台还有直播的时候，我试了下，下载直播流m3u8的时候，它是一个mp4一直变大，如果是回放的话，它等下载完了就可以打开，如果是直播的话，我刚刚中途停止了，这个mp4就打不开了。

**Comment by helson-lin** [comment]
直播的地址是m3u8协议的是嘛 我找个地址试试看

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月01日 16:53 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) |

你是创建了多个下载任务然后手动合成的嘛
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月01日 16:23 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | ISSUE Type download failed new features style questions other questions 非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。 Download Url 这个链接，中的视频都是直播流的m3u8，我想达到的效果是，因为没有回放，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。 Question Details please paste your question details below — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

您好，我不是创建了多个下载任务，我是docker里的ffandown，刚刚这个平台还有直播的时候，我试了下，下载直播流m3u8的时候，它是一个mp4一直变大，如果是回放的话，它等下载完了就可以打开，如果是直播的话，我刚刚中途停止了，这个mp4就打不开了。

**Comment by asong2022** [comment]
> 直播的地址是m3u8协议的是嘛 我找个地址试试看
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 16:53 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | 你是创建了多个下载任务然后手动合成的嘛 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月01日 16:23 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | ISSUE Type download failed new features style questions other questions 非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。 Download Url 这个链接，中的视频都是直播流的m3u8，我想达到的效果是，因为没有回放，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。 Question Details please paste your question details below — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 您好，我不是创建了多个下载任务，我是docker里的ffandown，刚刚这个平台还有直播的时候，我试了下，下载直播流m3u8的时候，它是一个mp4一直变大，如果是回放的话，它等下载完了就可以打开，如果是直播的话，我刚刚中途停止了，这个mp4就打不开了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

是的，直播流是m3u8协议，刚刚我发的那个平台链接估计五一了没其他直播了，那麻烦作者大大找个其他m3u8的直播地址试一试，直播m3u8的中断保存mp4真的我很想，因为太多直播没回放，直播过程中也会有中断的意外。
谢谢您。
还有想问下dingding推送的时候如何自定义通知呀，我看webhooks: 'https://oapi.dingtalk.com/robot/send?access_token=xxxx'，那$TEXT写在哪里呢send?title=$TEXT不知道加在哪里

**Comment by asong2022** [comment]
> 直播的地址是m3u8协议的是嘛 我找个地址试试看
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 16:53 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | 你是创建了多个下载任务然后手动合成的嘛 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月01日 16:23 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | ISSUE Type download failed new features style questions other questions 非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。 Download Url 这个链接，中的视频都是直播流的m3u8，我想达到的效果是，因为没有回放，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。 Question Details please paste your question details below — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 您好，我不是创建了多个下载任务，我是docker里的ffandown，刚刚这个平台还有直播的时候，我试了下，下载直播流m3u8的时候，它是一个mp4一直变大，如果是回放的话，它等下载完了就可以打开，如果是直播的话，我刚刚中途停止了，这个mp4就打不开了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

应该就是N_m3u8DL-CLI的这个功能“实时解密MP4分片”、“录制直播并开启实时合并”

**Comment by asong2022** [comment]
https://github.com/RikaCelery/N_m3u8DL-RE_Command_Generator/blob/main/main.png

**Comment by asong2022** [comment]
我们的下载直播流m3u8，也可以合并还是直接合成了mp4，就是打不开[N_m3u8DL-RE](https://github.com/RikaCelery/N_m3u8DL-RE_Command_Generator)可以设置录制直播时实时合并，合并成的是一整个ts，可以打开，作者大大可以看看为什么我们合成的直播视频打不开吗，真的很需要直播的合并

**Comment by asong2022** [comment]
> 直播的地址是m3u8协议的是嘛 我找个地址试试看
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 16:53 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | 你是创建了多个下载任务然后手动合成的嘛 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月01日 16:23 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] m3u8直播流的下载合并mp4无法打开 (Issue #30) | ISSUE Type download failed new features style questions other questions 非常好用！感谢您，部署在nas还能用快捷指令和油猴，就是我在使用过程中遇到了一个疑问，希望您能帮我一下。 Download Url 这个链接，中的视频都是直播流的m3u8，我想达到的效果是，因为没有回放，它边直播的时候我就边下载，最后直播停止时或者我手动取消时把前面下载的合并成mp4，目前我发现，能下载，但是这个mp4无法打开，麻烦作者大大帮帮我看一下。 Question Details please paste your question details below — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 您好，我不是创建了多个下载任务，我是docker里的ffandown，刚刚这个平台还有直播的时候，我试了下，下载直播流m3u8的时候，它是一个mp4一直变大，如果是回放的话，它等下载完了就可以打开，如果是直播的话，我刚刚中途停止了，这个mp4就打不开了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

[链接](https://iclasscloud.cretech.cn/livecloudceshi/index.html)
