### ISSUE TITLE
文件名称风格

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#31]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [x] style questions
- [ ] other questions

### Download Url

无关

### Question Details

下载文件命名的时候，我填了文件名称，它还是要在我填的文件名称后面加_数字后缀。还不是时间数字后缀

**Comment by helson-lin** [comment]
随机字符哦 下一个版本支持关闭

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月01日 18:01 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 文件名称风格 (Issue #31) |

ISSUE Type
download failed
new features
style questions
other questions
Download Url

无关

Question Details

下载文件命名的时候，我填了文件名称，它还是要在我填的文件名称后面加_数字后缀。还不是时间数字后缀

**Comment by asong2022** [comment]
> 随机字符哦 下一个版本支持关闭
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 18:01 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [helson-lin/ffandown] 文件名称风格 (Issue #31) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 下载文件命名的时候，我填了文件名称，它还是要在我填的文件名称后面加_数字后缀。还不是时间数字后缀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

谢谢！！作者大大太厉害了

**Comment by helson-lin** [comment]
最新v5.0.8_beat支持手动配置是否启动，默认不加时间戳

**Comment by asong2022** [comment]
> 最新v5.0.8_beta支持手动配置是否启动，默认不加时间戳

谢谢！成功了
