### ISSUE TITLE
机器人通过api发送url和name

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#32]
###  ISSUE Type

- [ ] download failed
- [x] new features
- [ ] style questions
- [ ] other questions

### Download Url

无关

### Question Details

请问下dingding机器人可以接收到默认文本的通知了，如何改成自定义的通知呢，变量$TEXT不知道如何加到dingding的webhooks地址进去。
还有就是既然dingding机器人可以收通知，那能否把快捷指令的方法，放进机器人里面，通过dingding的聊天窗口发送url和name实现创建下载任务，这些需要您的指点。

**Comment by helson-lin** [comment]
钉钉机器人目前不支持自定义文本 只有bark可以使用变量。关于机器人创建任务的问题 需要待我调研一下 五一期间可能发新版本

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月01日 18:04 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 机器人通过api发送url和name (Issue #32) |

ISSUE Type
download failed
new features
style questions
other questions
Download Url

无关

Question Details

请问下dingding机器人可以接收到默认文本的通知了，如何改成自定义的通知呢，变量$TEXT不知道如何加到dingding的webhooks地址进去。
还有就是既然dingding机器人可以收通知，那能否把快捷指令的方法，放进机器人里面，通过dingding的聊天窗口发送url和name实现创建下载任务，这些需要您的指点。

**Comment by asong2022** [comment]
> 钉钉机器人目前不支持自定义文本 只有bark可以使用变量。关于机器人创建任务的问题 需要待我调研一下 五一期间可能发新版本
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 18:04 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [helson-lin/ffandown] 机器人通过api发送url和name (Issue #32) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 请问下dingding机器人可以接收到默认文本的通知了，如何改成自定义的通知呢，变量$TEXT不知道如何加到dingding的webhooks地址进去。 还有就是既然dingding机器人可以收通知，那能否把快捷指令的方法，放进机器人里面，通过dingding的聊天窗口发送url和name实现创建下载任务，这些需要您的指点。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

太感谢您了！劳动节快乐！

**Comment by asong2022** [comment]
> 钉钉机器人不支持应答机制 找个功能可能没法实现 关于消息的自定义可以优化
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月01日 18:10 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] 机器人通过api发送url和name (Issue #32) | 钉钉机器人目前不支持自定义文本 只有bark可以使用变量。关于机器人创建任务的问题 需要待我调研一下 五一期间可能发新版本 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月01日 18:04 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] 机器人通过api发送url和name (Issue #32) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 请问下dingding机器人可以接收到默认文本的通知了，如何改成自定义的通知呢，变量$TEXT不知道如何加到dingding的webhooks地址进去。 还有就是既然dingding机器人可以收通知，那能否把快捷指令的方法，放进机器人里面，通过dingding的聊天窗口发送url和name实现创建下载任务，这些需要您的指点。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 太感谢您了！劳动节快乐！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢，那飞书机器人应该有应答机制，飞书应该可以
