### ISSUE TITLE
mp4视频的下载支持

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#33]
###  ISSUE Type

- [ ] download failed
- [x] new features
- [ ] style questions
- [ ] other questions

### Download Url

无关

### Question Details

是否可以考虑内置aria2或者增加aria2RPC功能用来下载现成的mp4视频呀，通过油猴直接发送，下载结束了还有通知的方式太舒适了

**Comment by helson-lin** [comment]
aria2不就支持rpc调用嘛 我可能没理解你的需求

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月02日 12:20 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) |

ISSUE Type
download failed
new features
style questions
other questions
Download Url

无关

Question Details

是否可以考虑内置aria2或者增加aria2RPC功能用来下载现成的mp4视频呀，通过油猴直接发送，下载结束了还有通知的方式太舒适了

**Comment by asong2022** [comment]
> aria2不就支持rpc调用嘛 我可能没理解你的需求
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月02日 12:20 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 是否可以考虑内置aria2或者增加aria2RPC功能用来下载现成的mp4视频呀，通过油猴直接发送，下载结束了还有通知的方式太舒适了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

我想通过ffandown的添加任务来完成mp4的下载

**Comment by asong2022** [comment]
> aria2不就支持rpc调用嘛 我可能没理解你的需求
> [...](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月02日 12:20 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 是否可以考虑内置aria2或者增加aria2RPC功能用来下载现成的mp4视频呀，通过油猴直接发送，下载结束了还有通知的方式太舒适了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

就是mp4的那种格式也希望能直接通过您的ffandown实现添加任务进行下载，就用不到打开aria2Ng了。

**Comment by helson-lin** [comment]
后面考虑添加

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月02日 15:19 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) |

aria2不就支持rpc调用嘛 我可能没理解你的需求
...
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月02日 12:20 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 是否可以考虑内置aria2或者增加aria2RPC功能用来下载现成的mp4视频呀，通过油猴直接发送，下载结束了还有通知的方式太舒适了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

就是mp4的那种格式也希望能直接通过您的ffandown实现添加任务进行下载，就用不到打开aria2Ng了。

**Comment by asong2022** [comment]
> 后面考虑添加
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月02日 15:19 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) | aria2不就支持rpc调用嘛 我可能没理解你的需求 ... ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月02日 12:20 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) | ISSUE Type download failed new features style questions other questions Download Url 无关 Question Details 是否可以考虑内置aria2或者增加aria2RPC功能用来下载现成的mp4视频呀，通过油猴直接发送，下载结束了还有通知的方式太舒适了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 就是mp4的那种格式也希望能直接通过您的ffandown实现添加任务进行下载，就用不到打开aria2Ng了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢！

**Comment by helson-lin** [comment]
最新v5.0.8_beat支持mp4下载

**Comment by dreampjk** [comment]
有docker版了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月25日(周六) 下午4:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [helson-lin/ffandown] mp4视频的下载支持 (Issue #33)




 
最新v5.0.8_beat支持mp4下载

**Comment by helson-lin** [comment]
发了 arm版本等会推送

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月25日 17:13 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] mp4视频的下载支持 (Issue #33) |

有docker版了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月25日(周六) 下午4:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [helson-lin/ffandown] mp4视频的下载支持 (Issue #33)





最新v5.0.8_beat支持mp4下载

**Comment by asong2022** [comment]
下载结束的通知变成了下载开始的通知了
