### ISSUE TITLE
下载过程不能中断

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#35]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [x] style questions
- [ ] other questions

### Download Url

[点播链接](https://encrypt-k-vod.xet.tech/9764a7a5vodtransgzp1252524126/95407852243791576541681116/drm/v.f421220.m3u8?sign=a569087f95f33bcf9e6eec93d64f3299&t=6637b1e5&us=UkoirHurpJ)
[直播链接](https://iclasscloud.cretech.cn/livecloudceshi/index.html)

### Question Details

下载过程不能中断，不管是直播流的还是点播的m3u8，都不能中途取消，取消了，合成的mp4就没有解密。

那请问下大佬是不是可以做到实时解密合并，实现下载到哪里可以中断在哪里。想在哪里停下来，就在哪里停。

**Comment by helson-lin** [comment]
最新v5.0.8_beat支持中断下载，要使用中止下载功能，不能暂停，暂停的无法播放

**Comment by asong2022** [comment]
> 最新v5.0.8_beat支持中断下载，要使用中止下载功能，不能暂停，暂停的无法播放

谢谢，那直播的等他结束直播是不是就可以正常播放了

**Comment by helson-lin** [comment]
你终止也可以的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月25日 19:01 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 下载过程不能中断 (Issue #35) |

最新v5.0.8_beat支持中断下载，要使用中止下载功能，不能暂停，暂停的无法播放

谢谢，那直播的等他结束直播是不是就可以正常播放了

**Comment by asong2022** [comment]
> 你终止也可以的
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月25日 19:01 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] 下载过程不能中断 (Issue #35) | 最新v5.0.8_beat支持中断下载，要使用中止下载功能，不能暂停，暂停的无法播放 谢谢，那直播的等他结束直播是不是就可以正常播放了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢！中止下载功能如何使用呢

**Comment by asong2022** [comment]
> 你终止也可以的
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月25日 19:01 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] 下载过程不能中断 (Issue #35) | 最新v5.0.8_beat支持中断下载，要使用中止下载功能，不能暂停，暂停的无法播放 谢谢，那直播的等他结束直播是不是就可以正常播放了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

在前端页面右下角的设置里面有字错了，出现两个视频质量的词条了

**Comment by asong2022** [comment]
> > 你终止也可以的 [...](#) ---- 回复的原邮件 ---- |发件人 |_**@**_。_**> | | 发送日期 | 2024年05月25日 19：01 | | 收件人 | helson-lin/ffandown _**@**_.**_> | |抄送人 |helson-lin _**@**_._**>，评论_**@**_。**_> | |主题 |Re： [helson-lin/ffandown] 下载过程不能中断 （Issue #35） |最新v5.0.8_beat支持中断下载，要使用中止下载功能，不能暂停，暂停的无法播放 谢谢，那直播的等他结束直播是不是就可以正常播放了 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> 
> 谢谢！中止下载功能如何使用呢，没看到中止下载功能的选项呀

看到了，x就是中止下载，感谢

**Comment by asong2022** [comment]
按了中止下载，中止不了，还有就是手机端的中止下载按钮出不来，切换ua也不行

**Comment by asong2022** [comment]
> 按了中止下载，中止不了，还有就是手机端的中止下载按钮出不来，切换ua也不行

可能是我拉的镜像不对，我用版本号获取一下docker pull h55205l/ffandown:v5.0.8-Beta
