### ISSUE TITLE
config支持配置默认视频质量和格式

### ISSUE THREAD

**Issue by 2284787774** [helson-lin/ffandown#36]
目前默认是medium和mp4，每次添加都要修改很麻烦

**Comment by helson-lin** [comment]
好的 下个版本优化 不过发布版本时间还不一定 目前项目就我一个人维护 时间有限

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月16日 13:10 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] config支持配置默认视频质量和格式 (Issue #36) |

目前默认是medium和mp4，每次添加都要修改很麻烦

**Comment by helson-lin** [comment]
最新v5.0.8_beat支持了
