### ISSUE TITLE
前端进度条百分比不显示

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#39]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [x] style questions
- [ ] other questions

### Question Details

前端进度条百分比不显示

**Comment by helson-lin** [comment]
请使用最新版本

**Comment by asong2022** [comment]
> 请使用最新版本

谢谢！但是由于网络问题，我现在不知道如何下载新版本了

**Comment by helson-lin** [comment]
> > 请使用最新版本
> 
> 
> 
> 谢谢！但是由于网络问题，我现在不知道如何下载新版本了

docker 用下加速镜像 GitHub release 也可以了

**Comment by asong2022** [comment]
> > > 请使用最新版本
> > 
> > 
> > 谢谢！但是由于网络问题，我现在不知道如何下载新版本了
> 
> docker 用下加速镜像 GitHub release 也可以了

最新版页面好像没有中止下载的功能了，就是直播可以中断然后文件还能播放的那个中止下载
