### ISSUE TITLE
能查看下载进度条吗

### ISSUE THREAD

**Issue by dreampjk** [helson-lin/ffandown#4]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [ ] style questions
- [ ] other questions

### Download Url

please  paste the url below
if it's not a special url can't download, please provide more urls

### Question Details

please paste your question details below

**Comment by helson-lin** [comment]
> > 这个需求看使用频率不高所以暂时没有考虑增加，看用户反馈和使用情况吧
> 
> 主要是想查看有没有下载完. 要不只能在docker日志里查看

有下载通知的，你配置文件里面配置，钉钉、飞书或者bark软件通知，下载成功失败会提示的

**Comment by helson-lin** [comment]
v5版本已经支持进度查看 目前为beta版本

**Comment by dreampjk** [comment]
v5有docker版吗

**Comment by helson-lin** [comment]
等周末稳定一点 会构建docker


目前功能不太稳定
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月23日 21:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
State ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 能查看下载进度条吗 (Issue #4) |

v5有docker版吗

**Comment by helson-lin** [comment]
v5.0.4-beta 版本已推送到docker hub x64平台arm平台没有构建版本

**Comment by dreampjk** [comment]
> v5.0.4-beta 版本已推送到docker hub x64平台arm平台没有构建版本

群晖不能直接访问docker  
V5拉取的版本 也是  latest  吗

**Comment by helson-lin** [comment]
不是latest 是v5.0.4-beta 用这个标签 群晖可以的点击下载的时候手动输入标签

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月26日 20:36 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
State ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 能查看下载进度条吗 (Issue #4) |

v5.0.4-beta 版本已推送到docker hub x64平台arm平台没有构建版本

群晖不能直接访问docker
V5拉取的版本 也是 latest 吗

**Comment by dreampjk** [comment]
> 不是latest 是v5.0.4-beta 用这个标签 群晖可以的点击下载的时候手动输入标签
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年11月26日 20:36 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, State ***@***.***> | | 主题 | Re: [helson-lin/ffandown] 能查看下载进度条吗 (Issue #4) | v5.0.4-beta 版本已推送到docker hub x64平台arm平台没有构建版本 群晖不能直接访问docker V5拉取的版本 也是 latest 吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

拉取成功了  谢谢

**Comment by helson-lin** [comment]
> > 不是latest 是v5.0.4-beta 用这个标签 群晖可以的点击下载的时候手动输入标签
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 发送日期 | 2023年11月26日 20:36 | | 收件人 | helson-lin/ffandown _**@**_.**_> | | 抄送人 | helson-lin _**@**_._**>, State _**@**_.**_> | | 主题 | Re: [helson-lin/ffandown] 能查看下载进度条吗 (Issue #4) | v5.0.4-beta 版本已推送到docker hub x64平台arm平台没有构建版本 群晖不能直接访问docker V5拉取的版本 也是 latest 吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 拉取成功了 谢谢

建议把/app/lib映射出去 依赖会下载到这里，如果下次更新镜像就不需要再次下载。不处理也不影响，下载很快

**Comment by dreampjk** [comment]
> > > 不是latest 是v5.0.4-beta 用这个标签 群晖可以的点击下载的时候手动输入标签
> > > […](#)
> > > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 发送日期 | 2023年11月26日 20:36 | | 收件人 | helson-lin/ffandown _**@**_.**_> | | 抄送人 | helson-lin _**@**_._**>, State _**@**_.**_> | | 主题 | Re: [helson-lin/ffandown] 能查看下载进度条吗 (Issue #4) | v5.0.4-beta 版本已推送到docker hub x64平台arm平台没有构建版本 群晖不能直接访问docker V5拉取的版本 也是 latest 吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> > 
> > 
> > 拉取成功了 谢谢
> 
> 建议把/app/lib映射出去 依赖会下载到这里，如果下次更新镜像就不需要再次下载。不处理也不影响，下载很快

不会操作  默认使用吧
