### ISSUE TITLE
油猴脚本优化

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#40]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [x] style questions
- [ ] other questions

### Question Details

既然可以下载mp4，是否可以优化一下油猴脚本，按一下也可以推送mp4了

**Comment by helson-lin** [comment]
后续计划优化

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月25日 22:45 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 油猴脚本优化 (Issue #40) |

ISSUE Type
download failed
new features
style questions
other questions
Question Details

既然可以下载mp4，是否可以优化一下油猴脚本，按一下也可以推送mp4了

**Comment by helson-lin** [comment]
脚本在重构当中，后续增加mp4支持

**Comment by dreampjk** [comment]
> 脚本在重构当中，后续增加mp4支持

有新版本了吗

**Comment by helson-lin** [comment]
版本可能周末发 暂定

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月12日 21:07 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 油猴脚本优化 (Issue #40) |

脚本在重构当中，后续增加mp4支持

有新版本了吗

**Comment by helson-lin** [comment]
啥网站有mp4的资源 麻烦提供一下

**Comment by asong2022** [comment]
> 啥网站有mp4的资源 麻烦提供一下

https://teacher.knowbox.cn/#/teacher/meeting/package/817?courseId=103086

**Comment by helson-lin** [comment]
https://file.io/2e9Q76OYJ2Av  测试版本 你可以测试用用看

**Comment by asong2022** [comment]
> https://file.io/2e9Q76OYJ2Av 测试版本 你可以测试用用看

已经被删除了

**Comment by helson-lin** [comment]
https://file.helson-lin.cn/picgobundle.js  托管平台删除了 你用这个吧

**Comment by asong2022** [comment]
> https://file.helson-lin.cn/picgobundle.js 托管平台删除了 你用这个吧

谢谢！FFANDOWN_URL=怎么改呀

**Comment by helson-lin** [comment]
新版本不需要修改了 点击icon设置
<img width="1764" alt="image" src="https://github.com/helson-lin/ffandown/assets/84565447/091a89ae-81bd-4a0d-81a1-9e9f4bfebb41">

**Comment by asong2022** [comment]
> 新版本不需要修改了 点击icon设置 <img alt="image" width="1764" src="https://private-user-images.githubusercontent.com/84565447/339798960-091a89ae-81bd-4a0d-81a1-9e9f4bfebb41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzU4OTgsIm5iZiI6MTcxODM3NTU5OCwicGF0aCI6Ii84NDU2NTQ0Ny8zMzk3OTg5NjAtMDkxYTg5YWUtODFiZC00YTBkLTgxYTEtOWU5ZjRiZmViYjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MzMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MTYxZWVkOGU5MzhjNTY0ZTdjZjdjN2RjNTNhMDFmMGQyNjJkZTg3MmMzMmU0NGZiOTNiYTNmNjMwZGMzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buTCyB8l9rHOUYgWI84Cly8xrz6aYQ_2qND2X4ipwuE">

![image](https://github.com/helson-lin/ffandown/assets/118357167/bd2f5675-d2cf-4f61-a100-096043dc4af7)
看不懂的错误

**Comment by helson-lin** [comment]
警告可以忽略

**Comment by asong2022** [comment]
> 警告可以忽略

谢谢！可以用的，就是成功推送了的图标不是绿色箭头，反而是红色叉，同一个网页标题的多个mp4，会被同个名字覆盖掉

**Comment by helson-lin** [comment]
> > 警告可以忽略
> 
> 谢谢！可以用的，就是成功推送了的图标不是绿色箭头，反而是红色叉，同一个网页标题的多个mp4，会被同个名字覆盖掉

名称是从标题获取的 后面会讲名称后面加上序号

**Comment by helson-lin** [comment]
> > > 警告可以忽略
> > 
> > 
> > 谢谢！可以用的，就是成功推送了的图标不是绿色箭头，反而是红色叉，同一个网页标题的多个mp4，会被同个名字覆盖掉
> 
> 名称是从标题获取的 后面会讲名称后面加上序号

Ui设计我不是很在行都是随意弄的 成功发送是绿色的通知消息

**Comment by asong2022** [comment]
> > > > 警告可以忽略
> > > 
> > > 
> > > 谢谢！可以用的，就是成功推送了的图标不是绿色箭头，反而是红色叉，同一个网页标题的多个mp4，会被同个名字覆盖掉
> > 
> > 
> > 名称是从标题获取的 后面会讲名称后面加上序号
> 
> Ui设计我不是很在行都是随意弄的 成功发送是绿色的通知消息

嗯嗯谢谢！能下直播已经是太酷了。

**Comment by helson-lin** [comment]
> > > > > 警告可以忽略
> > > > 
> > > > 
> > > > 谢谢！可以用的，就是成功推送了的图标不是绿色箭头，反而是红色叉，同一个网页标题的多个mp4，会被同个名字覆盖掉
> > > 
> > > 
> > > 名称是从标题获取的 后面会讲名称后面加上序号
> > 
> > 
> > Ui设计我不是很在行都是随意弄的 成功发送是绿色的通知消息
> 
> 嗯嗯谢谢！能下直播已经是太酷了。

目前更新频次不会太高 目前一个人维护 精力有限

**Comment by asong2022** [comment]
> 目前更新频次不会太高 目前一个人维护 精力有限

辛苦了！！谢谢您

**Comment by asong2022** [comment]
> > > 警告可以忽略
> > 
> > 
> > 谢谢！可以用的，就是成功推送了的图标不是绿色箭头，反而是红色叉，同一个网页标题的多个mp4，会被同个名字覆盖掉
> 
> 名称是从标题获取的 后面会讲名称后面加上序号

老脚本蛮好用的，电脑端一点就推送了，就不用自己复制粘贴了
