### ISSUE TITLE
v5.0.8-Beta  有编译的exe版本文件吗

### ISSUE THREAD

**Issue by DingQi1888** [helson-lin/ffandown#42]
v5.0.8-Beta  有编译的exe版本文件吗

**Comment by helson-lin** [comment]
晚点编译一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月31日 17:55 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] v5.0.8-Beta 有编译的exe版本文件吗 (Issue #42) |

v5.0.8-Beta 有编译的exe版本文件吗

**Comment by DingQi1888** [comment]
来信已收到，请等待回复

**Comment by helson-lin** [comment]
https://www.123pan.com/s/WNhDVv-pDIUh.html

**Comment by DingQi1888** [comment]
非常感谢

**Comment by DingQi1888** [comment]
Error: Cannot find module 'C:\snapshot\ffandown\node_modules\.pnpm\sqlite3@5.1.6\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node'
Require stack:
- C:\snapshot\ffandown\node_modules\.pnpm\sqlite3@5.1.6\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\snapshot\ffandown\node_modules\.pnpm\sqlite3@5.1.6\node_modules\sqlite3\lib\sqlite3.js
- C:\snapshot\ffandown\node_modules\.pnpm\oimi-helper@1.3.3\node_modules\oimi-helper\src\sql\entity.js
- C:\snapshot\ffandown\node_modules\.pnpm\oimi-helper@1.3.3\node_modules\oimi-helper\src\sql\index.js
- C:\snapshot\ffandown\node_modules\.pnpm\oimi-helper@1.3.3\node_modules\oimi-helper\src\index.js
- C:\snapshot\ffandown\bootstrap.js

**Comment by helson-lin** [comment]
我忘记了 没给你把依赖丢进去

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月01日 11:45 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] v5.0.8-Beta 有编译的exe版本文件吗 (Issue #42) |

Error: Cannot find module ***@***.***\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node'
Require stack:

***@***.***\node_modules\sqlite3\lib\sqlite3-binding.js
***@***.***\node_modules\sqlite3\lib\sqlite3.js
***@***.***\node_modules\oimi-helper\src\sql\entity.js
***@***.***\node_modules\oimi-helper\src\sql\index.js
***@***.***\node_modules\oimi-helper\src\index.js
C:\snapshot\ffandown\bootstrap.js

**Comment by helson-lin** [comment]
把这个文件放在程序同级目录就行了： [node_sqlite3.node](https://github.com/helson-lin/pkg_sqlite/raw/main/package/windows_x64_node_sqlite3.node)

**Comment by helson-lin** [comment]
> 把这个文件放在程序同级目录就行了： [node_sqlite3.node](https://github.com/helson-lin/pkg_sqlite/raw/main/package/windows_x64_node_sqlite3.node)

记得将文件重命名为：node_sqlite3.node

**Comment by DingQi1888** [comment]
C:\snapshot\ffandown\node_modules\.pnpm\node-fetch@2.6.9\node_modules\node-fetch\lib\index.js:1505
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://ipera.oimi.space/https://api.github.com/repos/helson-lin/ffandown-front/releases/latest failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\snapshot\ffandown\node_modules\.pnpm\node-fetch@2.6.9\node_modules\node-fetch\lib\index.js:1505:11)

看起来是ipera.oimi.space需要梯子   系统代理梯子也过不去   能否这个优化下

**Comment by helson-lin** [comment]
这是检查最新版的前端文件地址 接口请求失败了 由于静态文件是托管在 github api 被墙 只能走代理地址 我的代理服务是在vercel 估计你本地无法连接

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月02日 11:30 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] v5.0.8-Beta 有编译的exe版本文件吗 (Issue #42) |

***@***.***\node_modules\node-fetch\lib\index.js:1505
reject(new FetchError(request to ${request.url} failed, reason: ${err.message}, 'system', err));
^
FetchError: request to https://ipera.oimi.space/https://api.github.com/repos/helson-lin/ffandown-front/releases/latest failed, reason: read ECONNRESET
at ClientRequest. ***@***.***\node_modules\node-fetch\lib\index.js:1505:11)

看起来是ipera.oimi.space需要梯子 系统代理梯子也过不去 能否这个优化下

**Comment by helson-lin** [comment]
最新v5.0.9-beta 支持 release 打包了

**Comment by helson-lin** [comment]
> C:\snapshot\ffandown\node_modules.pnpm\node-fetch@2.6.9\node_modules\node-fetch\lib\index.js:1505 reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err)); ^ FetchError: request to https://ipera.oimi.space/https://api.github.com/repos/helson-lin/ffandown-front/releases/latest failed, reason: read ECONNRESET at ClientRequest. (C:\snapshot\ffandown\node_modules.pnpm\node-fetch@2.6.9\node_modules\node-fetch\lib\index.js:1505:11)
> 
> 看起来是ipera.oimi.space需要梯子 系统代理梯子也过不去 能否这个优化下

这个接口，我后面考虑自己单独维护了，不走 github 的 api。比较大部分人都是被墙的无法访问。
