### ISSUE TITLE
docker镜像启动不了，看上去是主页无法访问导致？

### ISSUE THREAD

**Issue by bnaand** [helson-lin/ffandown#45]
查看日志内容如下：
[ffandown] ffmpeg: env variable is set successfully
[ffandown] ffprobe: env variable is set successfully
[ffandown] Database synced successfully
/snapshot/ffandown/node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js:1505
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://ipera.oimi.space/https://api.github.com/repos/helson-lin/ffandown-front/releases/latest failed, reason: getaddrinfo ENOTFOUND ipera.oimi.space

**Comment by helson-lin** [comment]
前端文件下载失败了 建议把 public 文件夹映射出来 然后前端的静态文件去仓库下载 release 丢进去就好了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月15日 16:40 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] docker镜像启动不了，看上去是主页无法访问导致？ (Issue #45) |

查看日志内容如下：
[ffandown] ffmpeg: env variable is set successfully
[ffandown] ffprobe: env variable is set successfully
[ffandown] Database synced successfully
***@***.***/node_modules/node-fetch/lib/index.js:1505
reject(new FetchError(request to ${request.url} failed, reason: ${err.message}, 'system', err));
^
FetchError: request to https://ipera.oimi.space/https://api.github.com/repos/helson-lin/ffandown-front/releases/latest failed, reason: getaddrinfo ENOTFOUND ipera.oimi.space

**Comment by helson-lin** [comment]
不好意思 你再重启试试看 我域名忘记续费过期了 刚续费了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月15日 16:40 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] docker镜像启动不了，看上去是主页无法访问导致？ (Issue #45) |

查看日志内容如下：
[ffandown] ffmpeg: env variable is set successfully
[ffandown] ffprobe: env variable is set successfully
[ffandown] Database synced successfully
***@***.***/node_modules/node-fetch/lib/index.js:1505
reject(new FetchError(request to ${request.url} failed, reason: ${err.message}, 'system', err));
^
FetchError: request to https://ipera.oimi.space/https://api.github.com/repos/helson-lin/ffandown-front/releases/latest failed, reason: getaddrinfo ENOTFOUND ipera.oimi.space
