### ISSUE TITLE
请问能否在菜单里加一个直接复制资源链接的选项呢？

### ISSUE THREAD

**Issue by 921j** [helson-lin/ffandown#46]
因为我这边 Win10 运行 ffandown 直接闪退，所以我还是用你的脚本和“m3u8批量下载器”这个工具，目前它还挺好用的，就是每次需要点图标、点“查看资源”，点击链接复制，然后因为有弹窗所以还需要点一下其他地方关闭它……这样要下载多个页面的资源时就有点小繁琐，请问能否直接在脚本图标的菜单里增加一个“复制链接”和“复制标题”的选项呢？谢谢了！

**Comment by helson-lin** [comment]
油猴脚本是吧，这个是ui优化的过后的效果。有点不明白你的意思，可以话的麻烦画一下示意图，然后在脚本的仓库发 [issue](https://github.com/helson-lin/ffandown-violentmonkey-script)

**Comment by 921j** [comment]
好的，已发。

**Comment by helson-lin** [comment]
需求转移脚本仓库
