### ISSUE TITLE
群晖部署完成，日志显示完成和地址，但是打开就报错

### ISSUE THREAD

**Issue by iwhisper1011** [helson-lin/ffandown#47]
群晖部署完成，日志显示完成和地址，但是打开就报错

![PixPin_2024-10-03_23-28-37](https://github.com/user-attachments/assets/6d120805-57ff-408a-a60b-59b058f8e51f)

![PixPin_2024-10-03_23-30-17](https://github.com/user-attachments/assets/92667894-2170-47e2-9b86-92f68598ff4b)
不知什么原因

**Comment by helson-lin** [comment]
public 目录映射出来了嘛 前端文件在 public 里面不应该是下载失败了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月03日 23:31 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) |

群晖部署完成，日志显示完成和地址，但是打开就报错

PixPin_2024-10-03_23-28-37.png (view on web)

PixPin_2024-10-03_23-30-17.png (view on web)
不知什么原因

**Comment by iwhisper1011** [comment]
映射了 /app/public ，把文件拷进去了，要不容器会报错，现在应该是正常运行了的。

**Comment by iwhisper1011** [comment]
但是，现在无法打开界面，提示错误，如上图1

**Comment by helson-lin** [comment]
重启容器了嘛

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月03日 23:36 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) |

但是，现在无法打开界面，提示错误，如上图1

**Comment by helson-lin** [comment]
无法自动下载是因为前端发布版本依赖 GitHub 国内网络环境导致的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月03日 23:36 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) |

但是，现在无法打开界面，提示错误，如上图1

**Comment by iwhisper1011** [comment]
> 重启容器了嘛
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年10月03日 23:36 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | helson-lin ***@***.***>, Comment ***@***.***> | | 主题 | Re: [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) | 但是，现在无法打开界面，提示错误，如上图1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

重启过了，好几次了。

**Comment by helson-lin** [comment]
我看下你的public 目录下面文件结构

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月03日 23:41 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) |

重启容器了嘛
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年10月03日 23:36 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | helson-lin @.>, Comment @.> | | 主题 | Re: [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) | 但是，现在无法打开界面，提示错误，如上图1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

重启过了，好几次了。

**Comment by iwhisper1011** [comment]
解压后，可以了。谢谢大佬

**Comment by helson-lin** [comment]
需要解压放在 public 里面 public 里面应该是assets  和index.html 这些文件

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月03日 23:45 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 群晖部署完成，日志显示完成和地址，但是打开就报错 (Issue #47) |

default.png (view on web)

**Comment by iwhisper1011** [comment]
![图片](https://github.com/user-attachments/assets/47cf190b-75ad-43e0-9244-0b10d3ae9ffd)
速度有点问题，比我手机下的要慢的多。。。
