### ISSUE TITLE
TAG  arm64的镜像中public目录文件去哪里可以下载？

### ISSUE THREAD

**Issue by 1eexk** [helson-lin/ffandown#48]
使用[arm64-v5.0.9-Beta]的public目录下文件，打开是个空白页。

**Comment by helson-lin** [comment]
https://github.com/helson-lin/ffandown-front release 下载解压后丢入 即可

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月12日 10:25 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] TAG arm64的镜像中public目录文件去哪里可以下载？ (Issue #48) |

使用[arm64-v5.0.9-Beta]的public目录下文件，打开是个空白页。

**Comment by helson-lin** [comment]
你的网络环境访问不了 GitHub  API 导致前端依赖下载失败了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月12日 10:25 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] TAG arm64的镜像中public目录文件去哪里可以下载？ (Issue #48) |

使用[arm64-v5.0.9-Beta]的public目录下文件，打开是个空白页。

**Comment by 1eexk** [comment]
感谢，OK了。
