### ISSUE TITLE
linux arm版本的有吗 想安装到树莓派中 但是提示不支持arm

### ISSUE THREAD

**Issue by YoYoHC** [helson-lin/ffandown#5]
###  ISSUE Type
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by helson-lin** [comment]
docker不行的话，建议使用release版本，我这边没有单独为arm架构打包

**Comment by YoYoHC** [comment]
release 需要自己编译是吗

**Comment by helson-lin** [comment]
> release 需要自己编译是吗

不需要直接下载linux版本的
[https://github.com/helson-lin/ffandown/releases](https://github.com/helson-lin/ffandown/releases)

**Comment by helson-lin** [comment]
> 大佬能编译一个arm64 平台的吗 两个都没办法运行 提示 ffandown-linux: exec format error

可以，稍微晚点

**Comment by YoYoHC** [comment]
好 谢谢大佬 感谢感谢

**Comment by helson-lin** [comment]
> 好 谢谢大佬 感谢感谢
你试试看这个arm64的
[https://www.123pan.com/s/WNhDVv-83fUh.html](https://www.123pan.com/s/WNhDVv-83fUh.html)

**Comment by YoYoHC** [comment]
大佬这个怎么运行 我下载下来了 但是我不知道用什么命令运行 我太菜了 谢谢大佬！

**Comment by YoYoHC** [comment]
搞定了大佬 谢谢你！  怎么配置下载目录地址 我想下载到共享文件夹里面去

**Comment by helson-lin** [comment]
> 搞定了大佬 谢谢你！ 怎么配置下载目录地址 我想下载到共享文件夹里面去

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/84565447/235157486-672b87b5-737f-435c-8dae-b80f9092f610.png">

**Comment by YoYoHC** [comment]
谢谢了 大佬 运行起来了！！

**Comment by helson-lin** [comment]
> 谢谢了 大佬 运行起来了！！

没问题，我关闭了issue
