### ISSUE TITLE
docker容器启动失败，资源下载有问题

### ISSUE THREAD

**Issue by sunhaox** [helson-lin/ffandown#52]
```
# docker logs ffdandown
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
███████╗███████╗ █████╗ ███╗   ██╗██████╗  ██████╗ ██╗    ██╗███╗   ██╗
██╔════╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║    ██║████╗  ██║
█████╗  █████╗  ███████║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██╔██╗ ██║
██╔══╝  ██╔══╝  ██╔══██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██║╚██╗██║
██║     ██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║ ╚████║
╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝

[ffandown] ffprobe: env variable is set successfully
[ffandown] ffmpeg: env variable is set successfully
[ffandown] Database synced successfully
/snapshot/ffandown/node_modules/got/index.js:182
                                ee.emit('error', new got.RequestError(err, opts));
                                                 ^

GotError [RequestError]: getaddrinfo ENOTFOUND nn.oimi.space
    at ClientRequest.<anonymous> (/snapshot/ffandown/node_modules/got/index.js:182:22)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ENOTFOUND',
  host: 'nn.oimi.space',
  hostname: 'nn.oimi.space',
  method: 'GET',
  path: '/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.9/ffandown-frontend.zip',
  protocol: 'https:',
  url: 'https://nn.oimi.space/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.9/ffandown-frontend.zip'
}

Node.js v18.5.0
```

看log是下载前端文件时从`https://nn.oimi.space`下载失败。
能手动下载跳过网络下载吗？
能指定不从oimi.space下载直接从GitHub下载吗？

**Comment by helson-lin** [comment]
前端依赖下载失败了 需要手动处理

---- 回复的原邮件 ----
| 发件人 | Oliver ***@***.***> |
| 发送日期 | 2024年10月13日 12:15 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] docker容器启动失败，资源下载有问题 (Issue #52) |

# docker logs ffdandown
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
███████╗███████╗ █████╗ ███╗   ██╗██████╗  ██████╗ ██╗    ██╗███╗   ██╗
██╔════╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║    ██║████╗  ██║
█████╗  █████╗  ███████║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██╔██╗ ██║
██╔══╝  ██╔══╝  ██╔══██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██║╚██╗██║
██║     ██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║ ╚████║
╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝

[ffandown] ffprobe: env variable is set successfully
[ffandown] ffmpeg: env variable is set successfully
[ffandown] Database synced successfully
/snapshot/ffandown/node_modules/got/index.js:182
                                ee.emit('error', new got.RequestError(err, opts));
                                                 ^

GotError [RequestError]: getaddrinfo ENOTFOUND nn.oimi.space
    at ClientRequest.<anonymous> (/snapshot/ffandown/node_modules/got/index.js:182:22)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ENOTFOUND',
  host: 'nn.oimi.space',
  hostname: 'nn.oimi.space',
  method: 'GET',
  path: '/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.9/ffandown-frontend.zip',
  protocol: 'https:',
  url: 'https://nn.oimi.space/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.9/ffandown-frontend.zip'
}

Node.js v18.5.0


看log是下载前端文件时从https://nn.oimi.space下载失败。
能手动下载跳过网络下载吗？
能指定不从oimi.space下载直接从GitHub下载吗？

**Comment by helson-lin** [comment]
将 public 映射出来  https://github.com/helson-lin/ffandown-front release 下载解压后丢入 public

---- 回复的原邮件 ----
| 发件人 | Oliver ***@***.***> |
| 发送日期 | 2024年10月13日 12:15 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] docker容器启动失败，资源下载有问题 (Issue #52) |

# docker logs ffdandown
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
███████╗███████╗ █████╗ ███╗   ██╗██████╗  ██████╗ ██╗    ██╗███╗   ██╗
██╔════╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║    ██║████╗  ██║
█████╗  █████╗  ███████║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██╔██╗ ██║
██╔══╝  ██╔══╝  ██╔══██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██║╚██╗██║
██║     ██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║ ╚████║
╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═══╝

[ffandown] ffprobe: env variable is set successfully
[ffandown] ffmpeg: env variable is set successfully
[ffandown] Database synced successfully
/snapshot/ffandown/node_modules/got/index.js:182
                                ee.emit('error', new got.RequestError(err, opts));
                                                 ^

GotError [RequestError]: getaddrinfo ENOTFOUND nn.oimi.space
    at ClientRequest.<anonymous> (/snapshot/ffandown/node_modules/got/index.js:182:22)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ENOTFOUND',
  host: 'nn.oimi.space',
  hostname: 'nn.oimi.space',
  method: 'GET',
  path: '/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.9/ffandown-frontend.zip',
  protocol: 'https:',
  url: 'https://nn.oimi.space/https://github.com/helson-lin/ffandown-front/releases/download/v0.0.9/ffandown-frontend.zip'
}

Node.js v18.5.0


看log是下载前端文件时从https://nn.oimi.space下载失败。
能手动下载跳过网络下载吗？
能指定不从oimi.space下载直接从GitHub下载吗？

**Comment by sunhaox** [comment]
搞定，感谢❤
