### ISSUE TITLE
https://0472.org/hls/cgtn.m3u8这种直播下载，没有停止按钮，暂停后，mp4文件不能播放，是什么情况

### ISSUE THREAD

**Issue by xuwenxindeai** [helson-lin/ffandown#55]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [ ] style questions
- [ 1] other questions

### Download Url
https://0472.org/hls/cgtn.m3u8

找到停止按钮

### Question Details

please paste your question details below

**Comment by helson-lin** [comment]
问题和 #54 一样 已经修复，使用v5.1.0-Beta版本
