### ISSUE TITLE
希望添加，下载进度条

### ISSUE THREAD

**Issue by cuicsi** [helson-lin/ffandown#8]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [ ] style questions
- [ ] other questions

### Download Url

please  paste the url below
if it's not a special url can't download, please provide more urls

### Question Details

希望添加下载进度条，还有就是在意外关机的时候再次开机，不会继续下载

**Comment by helson-lin** [comment]
进度条的问题，在下一个版本新增。关于下载关机断开，重启继续下载。这个功能要进行技术验证理论上没啥问题。后续版本考虑添加。目前在重构版本所以比较慢

**Comment by cuicsi** [comment]
收到，感谢回答。在问一个问题
webhooks这个可以使用Server酱来调用来实现提醒吗？
我小白求告知

**Comment by helson-lin** [comment]
> 

server酱我没有研究过 等我看看 给你答复

**Comment by helson-lin** [comment]
> 
通知类型使用bark，地址案例：`https://sctapi.ftqq.com/SCT214651Ts163ve94I6BtTJEKB2mIWxFp.send?title=$TEXT`, $TEXT是下载内容变量

**Comment by cuicsi** [comment]
收到，我试一下

**Comment by cuicsi** [comment]
![IMG_20230628_095132](https://github.com/helson-lin/ffandown/assets/74813060/237f32a3-0d26-4663-b6a7-c9097f9dc6f4)
你看一下这样设置有没有问题？
刚才添加了一个任务，没有发送通知
通知会在什么情况下发送？

**Comment by helson-lin** [comment]
下载成功或者失败都会消息通知的
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月28日 09:53 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 希望添加，下载进度条 (Issue #8) |


你看一下这样设置有没有问题？
刚才添加了一个任务，没有发送通知
通知会在什么情况下发送？
