### ISSUE TITLE
这个是最新版docker镜像吗

### ISSUE THREAD

**Issue by dreampjk** [helson-lin/ffandown#9]
root@Synology:~# docker pull h55205l/ffandown:latest
latest: Pulling from h55205l/ffandown
Digest: sha256:1954b37a4f2700462a052d07ae5469fafe516e8545217def9d72a76b81a84229
Status: Image is up to date for h55205l/ffandown:latest
docker.io/h55205l/ffandown:latest
 docker打不开了  只能用命令更新了

![screenshot20230720](https://github.com/helson-lin/ffandown/assets/55814154/a5304ca6-fdfc-4dfb-be97-7d3e8ca295af)
能不能加个版本标识  我不知道我更新了没有

**Comment by helson-lin** [comment]
latest就是最新版本， 下次发版本我打上tag


在 2023年7月21日 ***@***.***> 写道：


***@***.***:~# docker pull h55205l/ffandown:latest
 latest: Pulling from h55205l/ffandown
 Digest: sha256:1954b37a4f2700462a052d07ae5469fafe516e8545217def9d72a76b81a84229
 Status: Image is up to date for h55205l/ffandown:latest
 docker.io/h55205l/ffandown:latest
 docker打不开了 只能用命令更新了

 能不能加个版本标识 我不知道我更新了没有
